version: "3.7"

services:
  manipulator:
    build: .
    container_name: manipulator
    tty: true
    volumes:
      - ./manipulator:/app
    entrypoint: ["python3", "manipulator.py", "--port", "50000"]
    networks:
      network:
        ipv4_address: 172.20.0.30
    


  controller:
    build: .
    container_name: controller
    tty: true
    volumes:
      - ./controller:/app
    entrypoint: ["python3", "controller.py",  "--destination",  "172.20.0.30:50000", "--port", "4000", "--server-port", "20000"]
    ports:
      - "20000:20000"
    networks:
      network:
        ipv4_address: 172.20.0.35


  sensor:
    build: .
    tty: true
    volumes:
      - ./sensor:/app
    entrypoint: ["python3", "sensor.py", "--destination",  "172.20.0.35:4000", "--port", "10000", "--times-per-second", "300"]
    networks:
      - network
    deploy:
      replicas: 8
        

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
