version: "3.7"

services:
  manipulator:
    build: .
    container_name: manipulator
    tty: true
    volumes:
      - ./manipulator:/app
    entrypoint: ["python3", "manipulator.py", "-p", "10000"]
    networks:
      network:
        ipv4_address: 172.20.0.5
    


  controller:
    build: .
    container_name: controller
    tty: true
    volumes:
      - ./controller:/app
    entrypoint: ["python3", "controller.py",  "-d",  "172.20.0.5:10000", "-p", "30000"]
    networks:
      network:
        ipv4_address: 172.20.0.2


  sensor:
    build: .
    container_name: sensor
    tty: true
    volumes:
      - ./sensor:/app
    entrypoint: ["python3", "sensor.py", "-d",  "172.20.0.2:30000", "-p", "5000"]
    networks:
      network:
        ipv4_address: 172.20.0.3

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
